server:
    port: 8091
amazon:
    dynamodb:
        endpoint: "https://dynamodb.ap-south-1.amazonaws.com"
    es:
     endpoint: "https://search-product-es-u4jrwstj4ev36wkjhbmhlv6odm.ap-south-1.es.amazonaws.com"
     region: "ap-south-1"
    aws:
     accessKey: "AKIATB6ZHMNIWZHZNYNA"
     secretKey: "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"




